/* tslint:disable */
/* eslint-disable */
/**
 * kroki-openapi-spec
 * kroki-openapi-spec(experimental)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * type of diagrams
 * @export
 */
export const DiagramType = {
  Actdiag: "actdiag",
  Blockdiag: "blockdiag",
  Bpmn: "bpmn",
  Bytefield: "bytefield",
  C4plantuml: "c4plantuml",
  Diagramsnet: "diagramsnet",
  Ditaa: "ditaa",
  Erd: "erd",
  Excalidraw: "excalidraw",
  Graphviz: "graphviz",
  Mermaid: "mermaid",
  Nomnoml: "nomnoml",
  Nwdiag: "nwdiag",
  Packetdiag: "packetdiag",
  Pikchr: "pikchr",
  Plantuml: "plantuml",
  Rackdiag: "rackdiag",
  Seqdiag: "seqdiag",
  Structurizr: "structurizr",
  Svgbob: "svgbob",
  Umlet: "umlet",
  Vega: "vega",
  Vegalite: "vegalite",
  Wavedrom: "wavedrom",
} as const;
export type DiagramType = typeof DiagramType[keyof typeof DiagramType];
