/* tslint:disable */
/* eslint-disable */
/**
 * kroki-openapi-spec
 * kroki-openapi-spec(experimental)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * image output format
 * @export
 */
export const OutputFormat = {
  Png: "png",
  Svg: "svg",
  Jpeg: "jpeg",
  Pdf: "pdf",
  Base64: "base64",
} as const;
export type OutputFormat = typeof OutputFormat[keyof typeof OutputFormat];
